<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.12">
  <POU Name="F_ClearLarge" Id="{bae5ec43-9172-01a4-1fc0-b20a0a42bb69}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_ClearLarge
VAR_IN_OUT CONSTANT
   stringToClear : LongString;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[MEMSET(ADR(stringToClear), 16#0, sizeof(stringToClear));]]></ST>
    </Implementation>
    <LineIds Name="F_ClearLarge">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>