<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.12">
  <POU Name="F_Concat6_Large" Id="{2c73f53f-ba11-02f8-2fc4-ede1b0cc1254}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_Concat6_Large : LongString
VAR_IN_OUT CONSTANT
   sOne : LongString;
   sTwo : LongString;
   sThree : LongString;
   sFour : LongString;
   sFive : LongString;
   sSix : LongString;
END_VAR
VAR
   str : LongString;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[str := F_Concat5_Large(sTwo, sThree, sFour, sFive, sSix);
F_Concat6_Large :=
   F_ConcatLarge(
      sOne,
      str
   );]]></ST>
    </Implementation>
    <LineIds Name="F_Concat6_Large">
      <LineId Id="1" Count="5" />
    </LineIds>
  </POU>
</TcPlcObject>