<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.12">
  <POU Name="F_Concat4" Id="{9ddea875-3099-0e12-2476-de81c38cd67d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_Concat4 : T_MaxString
VAR_INPUT
   sOne : STRING;
   sTwo : STRING;
   sThree : STRING;
   sFour : STRING;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_Concat4 := CONCAT(
   sOne,
   F_Concat3(sTwo, sThree, sFour)
);]]></ST>
    </Implementation>
    <LineIds Name="F_Concat4">
      <LineId Id="1" Count="3" />
    </LineIds>
  </POU>
</TcPlcObject>