<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.12">
  <POU Name="F_Concat5" Id="{d025524a-fc4c-05a6-31b7-401f6aad3e50}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_Concat5 : T_MaxString
VAR_INPUT
   sOne : STRING;
   sTwo : STRING;
   sThree : STRING;
   sFour : STRING;
   sFive : STRING;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_Concat5 := CONCAT(
   sOne,
   F_Concat4(sTwo, sThree, sFour, sFive)
);]]></ST>
    </Implementation>
    <LineIds Name="F_Concat5">
      <LineId Id="1" Count="3" />
    </LineIds>
  </POU>
</TcPlcObject>