<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.12">
  <POU Name="F_Concat7" Id="{e1a4f6c2-a528-06b9-0849-530a3890863e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_Concat7 : T_MaxString
VAR_INPUT
   sOne : STRING;
   sTwo : STRING;
   sThree : STRING;
   sFour : STRING;
   sFive : STRING;
   sSix : STRING;
   sSeven : STRING;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_Concat7 := CONCAT(
   sOne,
   F_Concat6(
      sTwo,
      sThree,
      sFour,
      sFive,
      sSix,
      sSeven
   )
);]]></ST>
    </Implementation>
    <LineIds Name="F_Concat7">
      <LineId Id="1" Count="10" />
    </LineIds>
  </POU>
</TcPlcObject>